version: "3"

services:
  mysql:
    image: mysql:8.0.31
    ports:
      - 3307:3306
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/config:/etc/mysql/conf.d
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rena
      MYSQL_USER: rena
      MYSQL_PASSWORD: 1234
      TZ: Asia/Seoul
    restart: always