spring:
  profiles:
    active: local

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

springdoc:
  api-docs:
    path: /swagger
    groups:
      enabled: true
  swagger-ui:
    enabled: true
    groups-order: ASC
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
    cache:
      disabled: true
    model-and-view-allowed: true